name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov

      - name: Collect coverage data
        run: cargo llvm-cov --cobertura --output-path coverage.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "20 80"
          
         # Upload the coverage.xml as an artifact for the next job
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  upload_coverage_to_influxdb:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Extract coverage percentage
        id: get_coverage
        run: |
          COVERAGE=$(grep 'line-rate' coverage.xml | awk -F'"' '{print $4 * 100}')
          echo "Coverage: $COVERAGE%"
          echo "::set-output name=coverage::$COVERAGE"

      - name: Upload coverage to InfluxDB
        run: |
          curl -X POST "${{ secrets.INFLUXDB_URL }}/api/v2/write?org=${{ secrets.INFLUXDB_ORG }}&bucket=${{ secrets.INFLUXDB_BUCKET }}&precision=s" \
          -H "Authorization: Token ${{ secrets.INFLUXDB_TOKEN }}" \
          --data-raw "rust_code_coverage,repository=${GITHUB_REPOSITORY},branch=master coverage=${{ steps.get_coverage.outputs.coverage }}"
