name: Rust

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
      name: Run tests
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"

      - name: Build and test
        run: |
          cargo build --verbose
          cargo test -q | grep "test result:" > test_coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: test_coverage.xml
