name: Rust

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov

      - name: Collect coverage data
        run: cargo llvm-cov --cobertura --output-path coverage.xml
          
         # Upload the coverage.xml as an artifact for the next job
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  upload_coverage_to_influxdb:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Extract coverage percentage
        id: get_coverage
        run: |
          LINE_RATE=$(grep -oP 'line-rate="\K[^"]*' coverage.xml | head -1)
          COVERAGE=$(echo "$LINE_RATE" | awk '{printf "%.2f", $1 * 100}')
          echo "Coverage: $COVERAGE%"
          echo "::set-output name=coverage::$COVERAGE"

      - name: Upload coverage to InfluxDB
        run: |
          curl -X POST "https://influx.eb-qute.eb-raptor.com/api/v2/write?org=2eaddcf5db9da1a0&bucket=48bc9e19d96e8721&precision=s" -H "Authorization: Token doan73lQJnEuNXy_WEb3fh3jeR7O8-iyRObOF4_40B2J0lRXgEzcHfaikI-5SJI9FQfdfM1KkOt5cTLLmXpryQ==" --data-raw "rust_code_coverage,repository=something,branch=aaa coverage=27.27"
